# See http://www.appveyor.com/docs/appveyor-yml for many more options

#Publish to PowerShell Gallery with this key
environment:
  NugetApiKey:
    secure: vB0dXo8QRs1fDxOi751+f3EypAyITprerMy2YkZPBaPucxaGyH2VpBl0J2JBs4IN

# Need the VS 2019 image b/c the rest all have a version of PowerShellGet that breaks
image: Visual Studio 2019

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Kick off the CI/CD pipeline
test_script:
  - pwsh: . .\build.ps1